application: brave-new-world-001
version: 1
runtime: python
api_version: 1

handlers:
- url: /resolvent/static
  static_dir: resolvent/static
- url: /resolvent/.*
  script: resolvent/main.py
- url: /
  script: index.py
