application: jon-caldwell
version: brave-new-world-001
runtime: python
api_version: 1

handlers:
- url: /resolvent/static
  static_dir: resolvent/static
- url: /resolvent/.*
  script: resolvent/main.py
- url: /syndicate/static
  static_dir: syndicate/static
- url: /syndicate/sync
  script: syndicate/main.py
  login: admin
- url: /syndicate/.*
  script: syndicate/main.py
- url: /
  script: index.py

inbound_services:
- warmup
